### PR TITLE
Changes from Temporal proposal

### PR DESCRIPTION
**Pull request by ptomato**
This covers the batch of normative changes that achieved consensus at the August 2021 TC39 meeting. I've ported the commits directly from the proposal-temporal repo.

### CODE REVIEW

**Review by justingrant — APPROVED** [review]
I didn't dig in to each code change in detail given that these were already reviewed over in proposal-temporal, but overall LGTM. Thanks for the work to pull together all these changes!

**Review by 12wrigja — APPROVED** [review]
Thanks!

**Comment by justingrant** [comment]
@Ms2ger - any concerns with this PR?  If not, I was planning to merge it ASAP because it touches so many places that merging any other PRs first might introduce merge conflicts.

**Comment by Ms2ger** [comment]
Sorry, didn't realize this was waiting on me.

**Pull request merged**
