### PR TITLE
Remove es-abstract dependency.

### PR DESCRIPTION
**Pull request by 12wrigja**

### CODE REVIEW

**Review by justingrant — APPROVED** [review]
🎉

**Comment by justingrant** [comment]
Is the next step to break up the `ES` object in ecmascript.ts into separate exported functions and then to import those functions (not `ES` overall) in all other files?

**Comment by 12wrigja** [comment]
I'm not sure it's strictly needed, but it seems like a relatively easy thing to do (and it's considered idiomatic Google TypeScript to not have "container objects" like this) so I was going to send a PR for that today.

**Comment by justingrant** [comment]
> I'm not sure it's strictly needed, but it seems like a relatively easy thing to do (and it's considered idiomatic Google TypeScript to not have "container objects" like this) so I was going to send a PR for that today.

Cool. I assume the main reason to do that would be to help with tree-shaking?

**Comment by 12wrigja** [comment]
My understanding is that tree-shaking is easier when the things to be shaken are module exports, but that this might only apply to some build tools and not others. E.g. I believe Closure Compiler can handle this and DCE the unused functions.

**Comment by justingrant** [comment]
Yep. Not sure if webpack's tree-shaking can handle it.  FWIW, I could help you test it by trying to build one of my apps (which is bundled with webpack) before and after your upcoming PR. I'll let you know if there's a bundle size diff.

**Pull request merged**
