### PR TITLE
Sync package-lock.json to package.json version

### PR DESCRIPTION
**Pull request by justingrant**
#27 didn't update the version in package-lock.json. I don't know what (if anything) this will break, but I assume they should be synced.

### CODE REVIEW

**Review by ptomato — APPROVED** [review]
Thanks! I also don't know what this affects, but I agree, this should be probably synced.

**Comment by 12wrigja** [comment]
Is it possible to add a test / check for this as part of merging a PR?

**Comment by ptomato** [comment]
This seems promising: https://stackoverflow.com/q/57998744/172999

**Comment by justingrant** [comment]
I've noticed that a some OSS libraries simply don't ship a package-lock.json at all. Not sure what the pros/cons of doing this are.

**Comment by ptomato** [comment]
The NPM utility itself encourages you to ship package-lock.json. It prevents you from getting different results locally / on CI / on users' machines, in the case where a newer version of a dependency has been released in between the last time you did `npm install` and the time when a user does `npm install`.

Personally I really hate checking in long autogenerated files that produce giant pull request diffs, but to me the above benefit weighs stronger than the dislike :smile:

**Pull request merged**
